// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Brian",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Brian",
            targets: ["AppModule"],
            bundleIdentifier: "me.alencar.jose.Brian",
            teamIdentifier: "NN9GWC737D",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .sparkle),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Unknown Usage Description")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("MLModels/MNISTClassifier.mlmodelc"),
                .copy("MLModels/YOLOv3TinyFP16.mlmodelc")
            ]
        )
    ]
)